version: "3.7"

services:
  # https://hub.docker.com/_/postgres
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: entity_search
    ports:
      - "5432:5432"
    command: postgres -c wal_writer_delay=20 -c wal_level=logical

  # https://pulsar.apache.org/docs/en/standalone/
  pulsar:
    image: apachepulsar/pulsar:2.9.1
    hostname: pulsar
    ports:
      - "8080:8080"
      - "6650:6650"
    command: bin/pulsar standalone

  # https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    environment:
      - node.name=es01
      - cluster.name=es-entity-search
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=changeme
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"

  # https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-docker.html
  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch



