version: "3.7"

services:
  # https://hub.docker.com/_/postgres
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: entity_search
    ports:
      - "5432:5432"
    command: postgres -c wal_writer_delay=20 -c wal_level=logical

  # https://pulsar.apache.org/docs/en/standalone/
  pulsar:
    image: apachepulsar/pulsar:2.9.1
    hostname: pulsar
    ports:
      - "8080:8080"
      - "6650:6650"
    command: bin/pulsar standalone
